import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createContext, runInContext } from 'node:vm';
const sandbox = { window: {} };
runInContext(readFileSync(new URL('./collaboration.js', import.meta.url), 'utf8'), createContext(sandbox));
const C = sandbox.window.BombCollaboration;
const keys = ['planner','plan_approval','implementer','auditor','verifier','acceptance'];
const build = (id, dependencies = []) => ({ id, round: 0, status: 'planning', spec: { objective: id, project_root: '/same/repo', roles: {} }, dependencies, steps: [] });
let graph = C.buildGraph([build('a'), build('b'), build('c',['a','b'])]);
assert.equal(graph.edges.length, 2);
assert.equal(graph.nodes.find(n => n.id === 'c').level, 1);
assert.equal(C.buildGraph([build('a'),build('b')]).edges.length, 0, 'shared folder cannot invent collaboration');
graph = C.buildGraph([build('c',['missing','missing'])]);
assert.equal(graph.edges.length, 1); assert.equal(graph.nodes.find(n => n.id === 'missing').kind, 'missing');
assert.equal(C.buildGraph([build('a',['b']),build('b',['a'])]).cycle, true, 'corrupt cycles are explicit');
const a = build('a');
a.status = 'ready_for_review';
a.progress = { basis:'workflow_checkpoints', completed:5, total:6, percent:83, round:0, checkpoints:keys.map((key,i)=>({key,label:key,completed:i<5,session_id:null})) };
assert.equal(C.progress(a).percent,83);
assert.equal(C.roleGraph(a).nodes.at(-1).state,'waiting');
const tampered = structuredClone(a); tampered.progress.percent = 100;
assert.equal(C.progress(tampered),null);
tampered.progress = structuredClone(a.progress); tampered.progress.round = 1;
assert.equal(C.progress(tampered),null, 'stale repair round must not show completion');
tampered.progress = structuredClone(a.progress); tampered.progress.completed = 6; tampered.progress.percent = 100; tampered.progress.checkpoints.at(-1).completed = true;
assert.equal(C.progress(tampered),null,'no 100 without acceptance');
assert.equal(C.progress(build('old')),null,'old hosts expose unknown');
a.steps = [{role:'auditor',round:0,session_id:'old-audit',output:'VERDICT: PASS\nChecked'}];
a.active_session_id = 'current-impl'; a.active_session_role = 'implementer'; a.active_session_round = 1; a.status = 'implementing'; a.round = 1; a.progress = null;
const roles = C.roleGraph(a).nodes;
assert.equal(roles.find(n=>n.id==='auditor').session, null,'old-round session cannot impersonate new auditor');
assert.equal(roles.find(n=>n.id==='implementer').session, 'current-impl');
assert.equal(C.sessionLink([a],'unrelated'),null);
assert.equal(C.sessionLink([a],'old-audit').role,'auditor','historical links retain recorded identity');
assert.equal(C.sessionLink([a],'current-impl').round,1);
for (const checkpoints of [Array(6).fill(null), Array(6).fill('bad')]) {
  const bad = structuredClone(tampered); bad.progress.checkpoints = checkpoints;
  assert.equal(C.progress(bad), null, 'malformed checkpoints produce unknown without throwing');
}
const huge = C.buildGraph(Array.from({length:150000},(_,i)=>build(String(i))));
const page = C.graphPage(huge, 2);
assert.equal(page.nodes.length,24); assert.equal(page.totalNodes,150000);
assert.equal(page.page,2); assert.equal(page.cycle,false);
console.log('collaboration.test.mjs: recorded edges, unknowns, stale rounds and human gates passed');
